name: package_deploy

on:
  push:
    branches:
    - master

jobs:
  package_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .npmrc for github packages
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.ACCESS_PACKAGES }}" >> ~/.npmrc
    - name: Set up node js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: https://npm.pkg.github.com/dex-company
    - name: Deploy
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.ACCESS_PACKAGES }
