name: testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up node js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        always-auth: true
        registry-url: https://npm.pkg.github.com/convex-dev
    - name: append token to .npmc file
      run: |
        echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> .npmrc
        cat .npmrc
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.5'
    - uses: DeLaGuardo/setup-clojure@2.0
      with:
        tools-deps: '1.10.1.483'
    - name: Install dependencies
      run: npm install
    - name: Build dependencies
      run: npm run build --if-present
    - name: Run Lint Test
      run: npm run lint
    - name: Install Surfer
      uses: actions/checkout@v2
      with:
        repository: DEX-Company/surfer
        token: ${{ secrets.ACCESS_TOKEN }}
        ref: develop
        path: surfer
    - name: Install dex-chain
      uses: actions/checkout@v2
      with:
        repository: DEX-Company/dex-chain
        ref: master
        path: dex-chain
    - name: Start dex-chain
      run: |
        docker login docker.pkg.github.com --username billbsing --password ${{ secrets.ACCESS_PACKAGES }}
        cd dex-chain
        ./start_dex_chain.sh test &
    - name : Start Surfer
      run: |
        cd surfer
        clojure -M:main &
        scritps/wait_for_surfer.sh
    - name: sleep and wait for dex-chain & surfer to load...
      run: sleep 50
    - name: Test
      run: npm test
      env:
        CI: true
