name: testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up node js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.5'
    - uses: DeLaGuardo/setup-clojure@2.0
      with:
        tools-deps: '1.10.1.483'
    - name: Install dependencies
      run: npm install
    - name: Build dependencies
      run: npm run build --if-present
    - name: Run Lint Test
      run: npm run lint
    - name: Install Surfer
      uses: actions/checkout@v1
      with:
        repository: DEX-Company/surfer
        token: ${{ secrets.ACCESS_TOKEN }}
        ref: develop
        path: surfer
    - name: Install dex-chain
      uses: actions/checkout@v1
      with:
        repository: DEX-Company/dex-chain
        ref: develop
        path: dex-chain
    - name: Start dex-chain
      run: |
        cd ../dex-chain
        ./start_dex_chain.sh test &
        sleep 30
    - name : Start Surfer
      run: |
        cd ../surfer
        clojure -M:main &
    - name: Wait for barge startup
      run: scripts/wait_for_migration_and_extract_keeper_artifacts.sh
    - name: Test
      run: npm test
      env:
        CI: true
    # adding docs in testing at the moment -- move to deploy later
    - name: Build Docs
      run: |
        npm run build:docs
        touch docs/.nojekyll
    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: docs/
